remote_theme: mx3m/hikari-for-jekyll
# Title of your blog; shows in the header
name: "Saw"

# Description of your content (will only be used on Google Search)
description: "Saw's Blog"

# Your name. Will show in your footer + sidebar
author: "Xue Zheng"

url: "http://saw235.github.io"
baseurl: "/hikari"

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I enjoy programming and mathematics."

# Social Accounts (mine, as placeholders)

twitter: mx3m
github: m3xm
dribbble: m3xm
instagram: m3xm

# Google Analytics (you may want to changes these with yours or even delete :)

#ga_domain: saw235.github.io
#ga_tracking_id: UA-47727049-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
plugins: [jekyll-paginate]
future: true

paginate: 20
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
